language: python

service:
- docker

python:
- "3.7"

env:
- DB=mysql

install:
- pip install -r requirements.txt

before_script: pip install docker-compose

script:
  - docker-compose run --rm django sh -c "pytest"