version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - MYSQL_DATABASE: "ecom"
      - MYSQL_USER: "root"
      - MYSQL_PASSWORD: "gluesys!!"
      - MYSQL_ROOT_PASSWORD: "gluesys!!"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command: 
      - python manage.py runserver 0:8000
    volumes:
      - ./:/app/