version: '3'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gluesys!!
      MYSQL_USER: ymkim
      MYSQL_PASSWORD: gluesys!!
      MYSQL_DATABASE: ecom

  django:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=ecom
      - DJANGO_DB_USERNAME=ymkim
      - DJANGO_DB_PASSWORD=gluesys!!
      - DJANGO_SECRET_KEY=5s-o54fcz87rly+c*e_z3jw614tye%3z*_2#0srga%j8)@i)3l
    ports:
      - "8000:8000"
    command: 
      - python manage.py runserver 0:8000
    volumes:
      - .:/code
    depends_on:
      - mysql