# Generated by Django 2.2.6 on 2019-12-18 14:10

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191212_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='static', upload_to='static'),
            preserve_default=False,
        ),
    ]
